name = "transparenta-eu-api"
account_id = "c53124cf4d8c039271e3d52917a56b96"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
API_BASE_URL = "https://transparenta-eu-api.bunnytech.app"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[[routes]]
pattern = "transparenta-eu-api.bunnytech.app"
custom_domain = true
