apiVersion: v1
kind: Secret
metadata:
  name: hack-for-facts-eb-client-secrets
  namespace: hack-for-facts-prod
type: Opaque
stringData:
  NODE_ENV: "production"
  VITE_APP_NAME: "Transparenta"
  VITE_APP_ENVIRONMENT: "production"
  VITE_API_URL: "https://api.transparenta.eu"
  VITE_SITE_URL: "https://transparenta.eu"
  VITE_POSTHOG_ENABLED: "false"
  VITE_POSTHOG_API_KEY: "REPLACE_ME"
  VITE_POSTHOG_HOST: "https://app.posthog.com"
  VITE_POSTHOG_PERSON_PROFILES: "identified_only"
  VITE_SENTRY_ENABLED: "false"
  VITE_SENTRY_DSN: "REPLACE_ME"
  VITE_SENTRY_TRACES_SAMPLE_RATE: "0.1"
  VITE_SENTRY_FEEDBACK_ENABLED: "false"
