---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBZVdOhAky218CmgaMpT2nSsVfsyAbrIH+bmneCuhR0I9WkTt3lsnXTyrYYeHD2zTXF4imZHK1Mjdqle6PDHKIn+9rXSje7Yymk5+ckfqAI5nAuu0dG/gZLI1q7vP6Py5Smpn2kDSOU6l1UBn5zQuMPC/ZjXqNqJheJ6FOT89XwnyjsidMrqCgXH1V3CcIqaGx3Vbr1n6wYyx8Y/VTHR2N7LjKQsNRWFN8OmJPUOENYbGHmevqmthy29e6iAlgJRgbz3n/Uu065ptGA0zigRL1OGV5WArYhIFzzNBOCaCPoYN31ABeOyutlvjo3OgZA3fNDKMttefiI7SNqad7kJxUVnxc4QyM0XuqrA7N5nmkLeWJ/8Z5Vlo3BgIdbHUAuvNPJY97xQn5pSBnLXodB+3wM8CnpU981mQk8SDOt3Nr37NVtMBl+zwFoBkcZ2ynPK9tswzx4y1xJ/z3ocJzvOn7jiG/trT8t1kloWxNdBW5TQ40tj8wp4Aiha9rIW4U7kzOc5Ynkw/qWnzHBD4ZrStngl4OadDPRfB0Pr9r5IJHR1A8fBKFk4/9PHDtWHaRinGz2gVGM5eioCTbtXesAIUg93N6Xn0RicYBrAYzPE0drHdLfc3zIqOykPucluQjwPZgZjawjAI80pIu99R8G1xiwjYs+8Qz69EvOhfc8jshrTHLjvbIh4SFGiiu7XOsS2ieOzpq+zNeQO3VGVtUemzqeIEmpUpBjyu7K+8yfnGjiM4b75IwYmKeo+G+pQyb+BWu4Cs6MRMELqwejpCa1Z8ie0js3zhR6pw3HjyeCppTG+9SHJa4wx8x5YMlplUpClDCObNKCThT5/45gZSMEkQ6bWVJioRWqEKitMGX/4B4FhnnSiHBTNPZCAPH2uQcQ3LG0vJ8kc/ptUsQuH7+/EkhCgzD40PPAharcUBCukGQntwVUMnUdjmKeOA==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
