---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials-client
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAeLZqU8NImJkheVVPZlOqiRygQ/mjsCC1yRvDQg2UAojoW0hHE4wDC1xidw0C3veK+rFsnUaRWzrFpjGieBOhNCkIJADAOlJ+2jJeB3IegNQZy2Wc8db/BChFaSWvTX+1ET79iUgHWwa5jaw7dXoJhuIKQYTnv0kEaWcwLLBHInCcgtplmAEExy4nOhC5G0C/BdX3EuM/xB/TBV6QEw8lF548e5nrtKi0HBR+SNoNlaaxK6bMsRb+G5gsKjWkbh69DEhZKV0Wjq5cikRNehSn4t2CvhyAEODa5QMYIwv50pd6EsRg3uJpJxtEry8cK+4XiMnkU1Ci40SGtz/ExZzpsUGn/V8yOWM44ieNe+NRx90Ua4AXpTuda76sPfLyTnNX9Wq/WazxacdhRxnRgjWUKzR5RZKhwpf2TrmtfmD6fmPuBTxD4EAWZu1V48c/JMCZvxJOWDw+zZIL8U0qXNd1lBu1QKGGtdWAjFK1Lp/DgD+vv6qw06PJ0jAOI+Eb3zj3CMWuJC18tfBCuEX5GrZdq5h32HbTrrYsCZRrS0AZNW/AAqiiEE4rdzfxZDQ/CSTofdivW6dczd137EGWUaeCw2SWXJGIN90ystc1Ud/Rxrvk/gJDytE1gtFK5ly76o3xqZZRnwTLIpvqmHpchamGdDtYSi+KsgEvpvYiHp41klWrl3vJ+vvMZhSnxWEml+IsZk06Hloom0kWvZy8+SILC+Ts/n6ZDK4KTd0+0Ezj/U8mR9Wd+NUFhITZrVjW1xq1qS1+mDYlKrqu0vJNKnVD4O33zkA517GLTccUUTlgsUAp6nV9KrrQUt4Tjiya9VUIo5LkF29lGkb41eY++xv+U+hw4ZKr4Btg6/Av7RGcRAAXF0i3Zc3pyY0qa8izhb9POogOA6rNwCgtJzPKUnb2ZLn7zR0AnmUSTjkNKeutVu8XQgoC7+SehRw==
  template:
    metadata:
      name: registry-credentials-client
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
