apiVersion: v1
kind: ConfigMap
metadata:
  name: hack-for-facts-eb-client-config
  namespace: hack-for-facts
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  APP_NAME: "hack-for-facts-eb-client"
  NODE_ENV: "production"
  APP_PORT: "3000"
  NITRO_HOST: "0.0.0.0"
  NITRO_PORT: "3000"
