apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hack-for-facts
resources:
- deployment.yaml
- hpa.yaml
- service.yaml
- virtual-service.yaml
- configmap.yaml
commonLabels:
  app.kubernetes.io/name: hack-for-facts-eb-client
  app.kubernetes.io/part-of: hack-for-facts
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hack-for-facts-eb-client
    spec:
      template:
        metadata:
          annotations:
            image-sha: af4e640a48388edfade6bb3080f16d6bc93927c0
  target:
    kind: Deployment
    name: hack-for-facts-eb-client
images:
- name: harbor.devostack.com/hack-for-facts/hack-for-facts-eb-client
  newName: harbor.devostack.com/hack-for-facts/hack-for-facts-eb-client
  newTag: af4e640a48388edfade6bb3080f16d6bc93927c0
