apiVersion: v1
kind: Service
metadata:
  name: hack-for-facts-eb-client
  namespace: hack-for-facts
spec:
  type: ClusterIP
  selector:
    app: hack-for-facts-eb-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
