apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: istio-transparenta-client-virtualservice
  namespace: hack-for-facts
spec:
  hosts:
    - "transparenta.eu"
  gateways:
    - istio-system/istio-https-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: hack-for-facts-eb-client
            port:
              number: 80
      retries:
        attempts: 2
        perTryTimeout: 4s
        retryOn: connect-failure,refused-stream,reset,5xx,gateway-error
      timeout: 15s
