apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hack-for-facts-dev

resources:
  - ../../base
  - ./secrets/sealed-app-secret.yaml
  - ./secrets/sealed-registry-secret.yaml

patches:
  - target:
      kind: Deployment
      name: hack-for-facts-eb-client
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hack-for-facts-dev

  - target:
      kind: Service
      name: hack-for-facts-eb-client
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hack-for-facts-dev

  - target:
      kind: VirtualService
      name: istio-transparenta-client-virtualservice
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hack-for-facts-dev
      - op: replace
        path: /spec/hosts/0
        value: "dev.transparenta.eu"

  - target:
      kind: ConfigMap
      name: hack-for-facts-eb-client-config
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: hack-for-facts-dev

  - target:
      kind: Deployment
      name: hack-for-facts-eb-client
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"

  - target:
      kind: HorizontalPodAutoscaler
      name: hack-for-facts-eb-client
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 1
